Better missing file errors
I tracked down https://github.com/mitsuhiko/insta/issues/380 at last.

This doesn't solve the problem, but does show which file is being deleted, so it's not such a mystery. A future PR could change how these are handled so it's more permissive.

For example:

```
error: File error for `/Users/maximilian/workspace/prql/prqlc/prqlc-parser/src/.lexer.rs.pending-snap': No such file or directory (os error 2)
```